#!/bin/bash
# Build the standalone gren-format CLI into ./app (run with `node app <args>`
# or, since it's executable, `./app <args>`). Marked +x so it also works
# unmodified as an npm `bin` target (see package.json).

set -e

cd "$(dirname "$0")"

# package.json's "version" is the single source of truth for the version, and
# `npm version <patch|minor|major>` is the only thing that bumps it. src/Version.gren
# -- what `gren-format --version` prints -- is GENERATED from it here, so there is
# no second string to keep in sync and no way to publish a binary that misreports
# its own version. The pattern must match something: an empty capture would
# otherwise generate `version = ""`.
pkg_version=$(sed -n 's/^[[:space:]]*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' package.json | head -1)
if [ -z "$pkg_version" ]; then
    echo "build.sh: could not find \"version\" in package.json" >&2
    exit 1
fi

read -r -d '' version_module <<EOF || true
module Version exposing (version)

{-| The version string \`gren-format --version\` prints.

**Generated by \`build.sh\` from \`package.json\`'s \`"version"\` — do not edit, and do
not bump it here.** \`npm version <patch|minor|major>\` is the only place a version
is bumped; \`build.sh\` regenerates this file from \`package.json\` before every
build, so a hand edit is overwritten on the next one.

It is committed rather than ignored so that a plain \`gren make Main\` works in a
fresh clone; \`build.sh\` rewrites it only when the version actually changed.

-}


{-| The current version, as it appears in \`package.json\`.
-}
version : String
version =
    "${pkg_version}"
EOF

# Rewrite only on a real change, so an unchanged build does not touch the file's
# mtime and force the compiler to redo work.
if [ "$version_module" != "$(cat src/Version.gren 2>/dev/null)" ]; then
    printf '%s\n' "$version_module" > src/Version.gren
    echo "build.sh: regenerated src/Version.gren for version ${pkg_version}"
fi

gren make Main
chmod +x app
